### ISSUE TITLE
Add option to filter out items already on a user's watchlist

### ISSUE THREAD

**Issue by sdl60660** [sdl60660/letterboxd_recommendations#6]
* Grab watchlist while scraping for ratings and return to the client
* Add checkbox for filtering out any items already on watchlist and maybe a badge marker on movies in recommendation list

**Comment by JackyKLai** [comment]
kinda similar to this, but I wonder if it's easy to take in a Letterboxd list and only recommend movies from that list. Requesting this feature since I'm too lazy to look up every movie on [The TIFF 2024 Lineup](https://letterboxd.com/tiff_net/list/2024-toronto-international-film-festival/) and decide which ones to get tickets to😆

**Comment by sdl60660** [comment]
Finally took care of this!

Between this PR: https://github.com/sdl60660/letterboxd_recommendations/pull/22
And these commits on main:
* https://github.com/sdl60660/letterboxd_recommendations/commit/de4f94c5de0058df5b06d6b18311c3bef8798601
* https://github.com/sdl60660/letterboxd_recommendations/commit/46420b245e82bd56b78cd73e5e55fb74fd6b28ab
* https://github.com/sdl60660/letterboxd_recommendations/commit/da2bca69eb7b1f28c499c3a8a2915e6d6a98ca76
* https://github.com/sdl60660/letterboxd_recommendations/commit/5dd712b7897cd112ca285e5da8e14913dc0b8d5a
* https://github.com/sdl60660/letterboxd_recommendations/commit/782d8b77ee7832ff434c6949cbf6e0e313792728
* https://github.com/sdl60660/letterboxd_recommendations/commit/32c7d7073efa0912fad89dd2d9ad33e9323b32a0
